vault:
  build: .
  ports:
    - "8200:8200"
  command: bash -c "/usr/bin/run-vault && vault server -config=config.hcl"

client:
  build: .
  command: vault init -address=http://vault:8200  -tls-skip-verify
  links:
    - vault
